package com.zhaochuninhefei.orm.comparison.mybatis.dao;

import com.zhaochuninhefei.orm.comparison.mybatis.po.PoConfigDict;
import com.zhaochuninhefei.orm.comparison.mybatis.po.PoConfigDictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@SuppressWarnings("JavadocDeclaration")
public interface PoConfigDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_dict
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    long countByExample(PoConfigDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_dict
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int deleteByExample(PoConfigDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_dict
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_dict
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int insert(PoConfigDict row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_dict
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int insertSelective(PoConfigDict row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_dict
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    List<PoConfigDict> selectByExample(PoConfigDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_dict
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    PoConfigDict selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_dict
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByExampleSelective(@Param("row") PoConfigDict row, @Param("example") PoConfigDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_dict
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByExample(@Param("row") PoConfigDict row, @Param("example") PoConfigDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_dict
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByPrimaryKeySelective(PoConfigDict row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_dict
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByPrimaryKey(PoConfigDict row);
}