package com.zhaochuninhefei.orm.comparison.mybatis.dao;

import com.zhaochuninhefei.orm.comparison.mybatis.po.PoCustomer;
import com.zhaochuninhefei.orm.comparison.mybatis.po.PoCustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@SuppressWarnings("JavadocDeclaration")
public interface PoCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    long countByExample(PoCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int deleteByExample(PoCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int insert(PoCustomer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int insertSelective(PoCustomer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    List<PoCustomer> selectByExample(PoCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    PoCustomer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByExampleSelective(@Param("row") PoCustomer row, @Param("example") PoCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByExample(@Param("row") PoCustomer row, @Param("example") PoCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByPrimaryKeySelective(PoCustomer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByPrimaryKey(PoCustomer row);
}