package com.zhaochuninhefei.orm.comparison.mybatis.dao;

import com.zhaochuninhefei.orm.comparison.dto.OrderDetailResult;
import com.zhaochuninhefei.orm.comparison.mybatis.po.PoOrderMain;
import com.zhaochuninhefei.orm.comparison.mybatis.po.PoOrderMainExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@SuppressWarnings("JavadocDeclaration")
public interface PoOrderMainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_main
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    long countByExample(PoOrderMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_main
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int deleteByExample(PoOrderMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_main
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_main
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int insert(PoOrderMain row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_main
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int insertSelective(PoOrderMain row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_main
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    List<PoOrderMain> selectByExampleWithBLOBs(PoOrderMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_main
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    List<PoOrderMain> selectByExample(PoOrderMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_main
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    PoOrderMain selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_main
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByExampleSelective(@Param("row") PoOrderMain row, @Param("example") PoOrderMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_main
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByExampleWithBLOBs(@Param("row") PoOrderMain row, @Param("example") PoOrderMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_main
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByExample(@Param("row") PoOrderMain row, @Param("example") PoOrderMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_main
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByPrimaryKeySelective(PoOrderMain row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_main
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(PoOrderMain row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_main
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByPrimaryKey(PoOrderMain row);

    List<OrderDetailResult> complexQueryByPage(@Param("regionCode") String regionCode,
                                               @Param("minActualPriceSum") Double minActualPriceSum);
}