package com.zhaochuninhefei.orm.comparison.mybatis.dao;

import com.zhaochuninhefei.orm.comparison.mybatis.po.PoProduct;
import com.zhaochuninhefei.orm.comparison.mybatis.po.PoProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@SuppressWarnings("JavadocDeclaration")
public interface PoProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    long countByExample(PoProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int deleteByExample(PoProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int insert(PoProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int insertSelective(PoProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    List<PoProduct> selectByExample(PoProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    PoProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByExampleSelective(@Param("row") PoProduct row, @Param("example") PoProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByExample(@Param("row") PoProduct row, @Param("example") PoProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByPrimaryKeySelective(PoProduct row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByPrimaryKey(PoProduct row);
}