package com.zhaochuninhefei.orm.comparison.mybatis.dao;

import com.zhaochuninhefei.orm.comparison.mybatis.po.PoProductCategory;
import com.zhaochuninhefei.orm.comparison.mybatis.po.PoProductCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@SuppressWarnings("JavadocDeclaration")
public interface PoProductCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    long countByExample(PoProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int deleteByExample(PoProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int insert(PoProductCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int insertSelective(PoProductCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    List<PoProductCategory> selectByExample(PoProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    PoProductCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByExampleSelective(@Param("row") PoProductCategory row, @Param("example") PoProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByExample(@Param("row") PoProductCategory row, @Param("example") PoProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByPrimaryKeySelective(PoProductCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByPrimaryKey(PoProductCategory row);
}