package com.zhaochuninhefei.orm.comparison.mybatis.dao;

import com.zhaochuninhefei.orm.comparison.mybatis.po.PoRegion;
import com.zhaochuninhefei.orm.comparison.mybatis.po.PoRegionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@SuppressWarnings("JavadocDeclaration")
public interface PoRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    long countByExample(PoRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int deleteByExample(PoRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int insert(PoRegion row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int insertSelective(PoRegion row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    List<PoRegion> selectByExample(PoRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    PoRegion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByExampleSelective(@Param("row") PoRegion row, @Param("example") PoRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByExample(@Param("row") PoRegion row, @Param("example") PoRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByPrimaryKeySelective(PoRegion row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByPrimaryKey(PoRegion row);
}