package com.zhaochuninhefei.orm.comparison.mybatis.dao;

import com.zhaochuninhefei.orm.comparison.mybatis.po.PoUserProfile;
import com.zhaochuninhefei.orm.comparison.mybatis.po.PoUserProfileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@SuppressWarnings("JavadocDeclaration")
public interface PoUserProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    long countByExample(PoUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int deleteByExample(PoUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int insert(PoUserProfile row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int insertSelective(PoUserProfile row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    List<PoUserProfile> selectByExampleWithBLOBs(PoUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    List<PoUserProfile> selectByExample(PoUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    PoUserProfile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByExampleSelective(@Param("row") PoUserProfile row, @Param("example") PoUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByExampleWithBLOBs(@Param("row") PoUserProfile row, @Param("example") PoUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByExample(@Param("row") PoUserProfile row, @Param("example") PoUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByPrimaryKeySelective(PoUserProfile row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByPrimaryKeyWithBLOBs(PoUserProfile row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    int updateByPrimaryKey(PoUserProfile row);

    /**
     * insertBatch
     *
     * @param records : The records to be inserted.
     * @return The number of rows affected.
     */
    int insertBatch(List<PoUserProfile> records);

    /**
     * updateByLevel
     *
     * @param params : The parameters to be updated.
     * @return The number of rows affected.
     */
    int updateByLevel(PoUserProfile params);
}