package com.zhaochuninhefei.orm.comparison.mybatis.po;

import java.time.LocalDateTime;

@SuppressWarnings({"LombokGetterMayBeUsed", "JavadocDeclaration", "LombokSetterMayBeUsed", "unused"})
public class PoConfigDict {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_dict.id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_dict.dict_code
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String dictCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_dict.dict_name
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String dictName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_dict.dict_value
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String dictValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_dict.dict_type
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String dictType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_dict.sort_order
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_dict.status
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_dict.remark
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_dict.create_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_dict.update_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private LocalDateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_dict.id
     *
     * @return the value of config_dict.id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_dict.id
     *
     * @param id the value for config_dict.id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_dict.dict_code
     *
     * @return the value of config_dict.dict_code
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_dict.dict_code
     *
     * @param dictCode the value for config_dict.dict_code
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode == null ? null : dictCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_dict.dict_name
     *
     * @return the value of config_dict.dict_name
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_dict.dict_name
     *
     * @param dictName the value for config_dict.dict_name
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setDictName(String dictName) {
        this.dictName = dictName == null ? null : dictName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_dict.dict_value
     *
     * @return the value of config_dict.dict_value
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getDictValue() {
        return dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_dict.dict_value
     *
     * @param dictValue the value for config_dict.dict_value
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setDictValue(String dictValue) {
        this.dictValue = dictValue == null ? null : dictValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_dict.dict_type
     *
     * @return the value of config_dict.dict_type
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getDictType() {
        return dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_dict.dict_type
     *
     * @param dictType the value for config_dict.dict_type
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setDictType(String dictType) {
        this.dictType = dictType == null ? null : dictType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_dict.sort_order
     *
     * @return the value of config_dict.sort_order
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_dict.sort_order
     *
     * @param sortOrder the value for config_dict.sort_order
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_dict.status
     *
     * @return the value of config_dict.status
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_dict.status
     *
     * @param status the value for config_dict.status
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_dict.remark
     *
     * @return the value of config_dict.remark
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_dict.remark
     *
     * @param remark the value for config_dict.remark
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_dict.create_time
     *
     * @return the value of config_dict.create_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_dict.create_time
     *
     * @param createTime the value for config_dict.create_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_dict.update_time
     *
     * @return the value of config_dict.update_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_dict.update_time
     *
     * @param updateTime the value for config_dict.update_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }
}