package com.zhaochuninhefei.orm.comparison.mybatis.po;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@SuppressWarnings({"LombokGetterMayBeUsed", "JavadocDeclaration", "LombokSetterMayBeUsed", "unused"})
public class PoCustomer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_no
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String customerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_name
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.email
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.phone
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_type
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Byte customerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.register_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private LocalDateTime registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.last_login_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private LocalDateTime lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.total_orders
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Integer totalOrders;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.total_consumption
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private BigDecimal totalConsumption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.status
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id
     *
     * @return the value of customer.id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id
     *
     * @param id the value for customer.id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_no
     *
     * @return the value of customer.customer_no
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getCustomerNo() {
        return customerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_no
     *
     * @param customerNo the value for customer.customer_no
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setCustomerNo(String customerNo) {
        this.customerNo = customerNo == null ? null : customerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_name
     *
     * @return the value of customer.customer_name
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_name
     *
     * @param customerName the value for customer.customer_name
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.email
     *
     * @return the value of customer.email
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.email
     *
     * @param email the value for customer.email
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.phone
     *
     * @return the value of customer.phone
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.phone
     *
     * @param phone the value for customer.phone
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_type
     *
     * @return the value of customer.customer_type
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Byte getCustomerType() {
        return customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_type
     *
     * @param customerType the value for customer.customer_type
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setCustomerType(Byte customerType) {
        this.customerType = customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.register_time
     *
     * @return the value of customer.register_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public LocalDateTime getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.register_time
     *
     * @param registerTime the value for customer.register_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setRegisterTime(LocalDateTime registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.last_login_time
     *
     * @return the value of customer.last_login_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public LocalDateTime getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.last_login_time
     *
     * @param lastLoginTime the value for customer.last_login_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setLastLoginTime(LocalDateTime lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.total_orders
     *
     * @return the value of customer.total_orders
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Integer getTotalOrders() {
        return totalOrders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.total_orders
     *
     * @param totalOrders the value for customer.total_orders
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setTotalOrders(Integer totalOrders) {
        this.totalOrders = totalOrders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.total_consumption
     *
     * @return the value of customer.total_consumption
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public BigDecimal getTotalConsumption() {
        return totalConsumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.total_consumption
     *
     * @param totalConsumption the value for customer.total_consumption
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setTotalConsumption(BigDecimal totalConsumption) {
        this.totalConsumption = totalConsumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.status
     *
     * @return the value of customer.status
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.status
     *
     * @param status the value for customer.status
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}