package com.zhaochuninhefei.orm.comparison.mybatis.po;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@SuppressWarnings({"LombokGetterMayBeUsed", "JavadocDeclaration", "LombokSetterMayBeUsed", "unused"})
public class PoOrderDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.product_id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.product_name
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.product_sku
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String productSku;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.quantity
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.unit_price
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private BigDecimal unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.total_price
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.discount
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private BigDecimal discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.actual_price
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private BigDecimal actualPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.create_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private LocalDateTime createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.id
     *
     * @return the value of order_detail.id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.id
     *
     * @param id the value for order_detail.id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_id
     *
     * @return the value of order_detail.order_id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.order_id
     *
     * @param orderId the value for order_detail.order_id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.product_id
     *
     * @return the value of order_detail.product_id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.product_id
     *
     * @param productId the value for order_detail.product_id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.product_name
     *
     * @return the value of order_detail.product_name
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.product_name
     *
     * @param productName the value for order_detail.product_name
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.product_sku
     *
     * @return the value of order_detail.product_sku
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getProductSku() {
        return productSku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.product_sku
     *
     * @param productSku the value for order_detail.product_sku
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setProductSku(String productSku) {
        this.productSku = productSku == null ? null : productSku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.quantity
     *
     * @return the value of order_detail.quantity
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.quantity
     *
     * @param quantity the value for order_detail.quantity
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.unit_price
     *
     * @return the value of order_detail.unit_price
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.unit_price
     *
     * @param unitPrice the value for order_detail.unit_price
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.total_price
     *
     * @return the value of order_detail.total_price
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.total_price
     *
     * @param totalPrice the value for order_detail.total_price
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.discount
     *
     * @return the value of order_detail.discount
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.discount
     *
     * @param discount the value for order_detail.discount
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.actual_price
     *
     * @return the value of order_detail.actual_price
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public BigDecimal getActualPrice() {
        return actualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.actual_price
     *
     * @param actualPrice the value for order_detail.actual_price
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setActualPrice(BigDecimal actualPrice) {
        this.actualPrice = actualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.create_time
     *
     * @return the value of order_detail.create_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.create_time
     *
     * @param createTime the value for order_detail.create_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }
}