package com.zhaochuninhefei.orm.comparison.mybatis.po;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@SuppressWarnings({"LombokGetterMayBeUsed", "JavadocDeclaration", "LombokSetterMayBeUsed", "unused"})
public class PoOrderMain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_main.id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_main.order_no
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_main.user_id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_main.region_code
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String regionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_main.total_amount
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private BigDecimal totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_main.discount_amount
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private BigDecimal discountAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_main.actual_amount
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private BigDecimal actualAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_main.order_status
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Byte orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_main.payment_method
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Byte paymentMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_main.payment_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private LocalDateTime paymentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_main.ship_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private LocalDateTime shipTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_main.finish_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private LocalDateTime finishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_main.receiver_name
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String receiverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_main.receiver_phone
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String receiverPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_main.receiver_address
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String receiverAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_main.create_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_main.update_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_main.remark
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_main.id
     *
     * @return the value of order_main.id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_main.id
     *
     * @param id the value for order_main.id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_main.order_no
     *
     * @return the value of order_main.order_no
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_main.order_no
     *
     * @param orderNo the value for order_main.order_no
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_main.user_id
     *
     * @return the value of order_main.user_id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_main.user_id
     *
     * @param userId the value for order_main.user_id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_main.region_code
     *
     * @return the value of order_main.region_code
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_main.region_code
     *
     * @param regionCode the value for order_main.region_code
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode == null ? null : regionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_main.total_amount
     *
     * @return the value of order_main.total_amount
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_main.total_amount
     *
     * @param totalAmount the value for order_main.total_amount
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_main.discount_amount
     *
     * @return the value of order_main.discount_amount
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public BigDecimal getDiscountAmount() {
        return discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_main.discount_amount
     *
     * @param discountAmount the value for order_main.discount_amount
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setDiscountAmount(BigDecimal discountAmount) {
        this.discountAmount = discountAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_main.actual_amount
     *
     * @return the value of order_main.actual_amount
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public BigDecimal getActualAmount() {
        return actualAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_main.actual_amount
     *
     * @param actualAmount the value for order_main.actual_amount
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setActualAmount(BigDecimal actualAmount) {
        this.actualAmount = actualAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_main.order_status
     *
     * @return the value of order_main.order_status
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Byte getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_main.order_status
     *
     * @param orderStatus the value for order_main.order_status
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setOrderStatus(Byte orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_main.payment_method
     *
     * @return the value of order_main.payment_method
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Byte getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_main.payment_method
     *
     * @param paymentMethod the value for order_main.payment_method
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setPaymentMethod(Byte paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_main.payment_time
     *
     * @return the value of order_main.payment_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public LocalDateTime getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_main.payment_time
     *
     * @param paymentTime the value for order_main.payment_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setPaymentTime(LocalDateTime paymentTime) {
        this.paymentTime = paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_main.ship_time
     *
     * @return the value of order_main.ship_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public LocalDateTime getShipTime() {
        return shipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_main.ship_time
     *
     * @param shipTime the value for order_main.ship_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setShipTime(LocalDateTime shipTime) {
        this.shipTime = shipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_main.finish_time
     *
     * @return the value of order_main.finish_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public LocalDateTime getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_main.finish_time
     *
     * @param finishTime the value for order_main.finish_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setFinishTime(LocalDateTime finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_main.receiver_name
     *
     * @return the value of order_main.receiver_name
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_main.receiver_name
     *
     * @param receiverName the value for order_main.receiver_name
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_main.receiver_phone
     *
     * @return the value of order_main.receiver_phone
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_main.receiver_phone
     *
     * @param receiverPhone the value for order_main.receiver_phone
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone == null ? null : receiverPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_main.receiver_address
     *
     * @return the value of order_main.receiver_address
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_main.receiver_address
     *
     * @param receiverAddress the value for order_main.receiver_address
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress == null ? null : receiverAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_main.create_time
     *
     * @return the value of order_main.create_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_main.create_time
     *
     * @param createTime the value for order_main.create_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_main.update_time
     *
     * @return the value of order_main.update_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_main.update_time
     *
     * @param updateTime the value for order_main.update_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_main.remark
     *
     * @return the value of order_main.remark
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_main.remark
     *
     * @param remark the value for order_main.remark
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}