package com.zhaochuninhefei.orm.comparison.mybatis.po;

@SuppressWarnings({"LombokGetterMayBeUsed", "JavadocDeclaration", "LombokSetterMayBeUsed", "unused"})
public class PoRegion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.region_code
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String regionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.region_name
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String regionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.parent_id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.level
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Byte level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.sort_order
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.status
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.id
     *
     * @return the value of region.id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.id
     *
     * @param id the value for region.id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.region_code
     *
     * @return the value of region.region_code
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.region_code
     *
     * @param regionCode the value for region.region_code
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode == null ? null : regionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.region_name
     *
     * @return the value of region.region_name
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.region_name
     *
     * @param regionName the value for region.region_name
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.parent_id
     *
     * @return the value of region.parent_id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.parent_id
     *
     * @param parentId the value for region.parent_id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.level
     *
     * @return the value of region.level
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.level
     *
     * @param level the value for region.level
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.sort_order
     *
     * @return the value of region.sort_order
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.sort_order
     *
     * @param sortOrder the value for region.sort_order
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.status
     *
     * @return the value of region.status
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.status
     *
     * @param status the value for region.status
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}