package com.zhaochuninhefei.orm.comparison.mybatis.po;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@SuppressWarnings({"LombokGetterMayBeUsed", "JavadocDeclaration", "LombokSetterMayBeUsed", "unused"})
public class PoUserProfile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.username
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.email
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.phone
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.age
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.gender
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.status
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.department
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.position
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.salary
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private BigDecimal salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.create_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.update_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.score
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private BigDecimal score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.level
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.description
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.id
     *
     * @return the value of user_profile.id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.id
     *
     * @param id the value for user_profile.id
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.username
     *
     * @return the value of user_profile.username
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.username
     *
     * @param username the value for user_profile.username
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.email
     *
     * @return the value of user_profile.email
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.email
     *
     * @param email the value for user_profile.email
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.phone
     *
     * @return the value of user_profile.phone
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.phone
     *
     * @param phone the value for user_profile.phone
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.age
     *
     * @return the value of user_profile.age
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.age
     *
     * @param age the value for user_profile.age
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.gender
     *
     * @return the value of user_profile.gender
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.gender
     *
     * @param gender the value for user_profile.gender
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.status
     *
     * @return the value of user_profile.status
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.status
     *
     * @param status the value for user_profile.status
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.department
     *
     * @return the value of user_profile.department
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.department
     *
     * @param department the value for user_profile.department
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.position
     *
     * @return the value of user_profile.position
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.position
     *
     * @param position the value for user_profile.position
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.salary
     *
     * @return the value of user_profile.salary
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public BigDecimal getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.salary
     *
     * @param salary the value for user_profile.salary
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.create_time
     *
     * @return the value of user_profile.create_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.create_time
     *
     * @param createTime the value for user_profile.create_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.update_time
     *
     * @return the value of user_profile.update_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.update_time
     *
     * @param updateTime the value for user_profile.update_time
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.score
     *
     * @return the value of user_profile.score
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.score
     *
     * @param score the value for user_profile.score
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.level
     *
     * @return the value of user_profile.level
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.level
     *
     * @param level the value for user_profile.level
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.description
     *
     * @return the value of user_profile.description
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.description
     *
     * @param description the value for user_profile.description
     *
     * @mbg.generated Wed Dec 31 11:56:54 CST 2025
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}